[tool.poetry]
name = "zbundler"
version = "0.1.0"
description = ""
authors = ["Fayssal El Mofatiche <fayssal.elmofatiche@dnbf.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
